# Generated by Django 2.1.7 on 2019-03-15 18:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('job_track_api', '0003_auto_20190311_2154'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskHourLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.DecimalField(decimal_places=2, max_digits=12)),
                ('log_date', models.DateField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taskHourLogs', to='job_track_api.Task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taskHourLogs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
