# Generated by Django 2.1.7 on 2019-03-15 19:52

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('job_track_api', '0004_taskhourlog'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TaskHourLog',
            new_name='TaskLog',
        ),
    ]
