# Generated by Django 2.1.7 on 2019-03-15 21:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job_track_api', '0006_auto_20190315_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklog',
            name='user',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='taskHourLogs', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
